fix buffer check bug
Maxim-Mazurok/SAX-TypeScript pull request #5
Opened 2021-10-14 02:22 UTC by kuboon

Some buffuers have `undefined` at beginning.
When `checkBufferLength` called, the `undefined` buffer will fail to receive `.length`

2021-10-14 02:32 UTC, Maxim-Mazurok requested changes
@kuboon thank you so much for your contribution! Your fix seems to be working as expected. Could you, please, add a test for this case, so that we won't break this in future releases?

2022-08-29 11:32 UTC, SvanteRichter commented
@kuboon Do you have an minimal example XML that does this? I run into this on basically all mediawiki dumps (tried on english wikivoyage, wiktionary and wikipedia) but I can't see what is actually causing it to be able to write a test for it. It'd be great to get this fixed and merged.

2022-08-29 11:57 UTC, Maxim-Mazurok commented
> @kuboon Do you have an minimal example XML that does this? I run into this on basically all mediawiki dumps (tried on english wikivoyage, wiktionary and wikipedia) but I can't see what is actually causing it to be able to write a test for it. It'd be great to get this fixed and merged.

@SahAssar perhaps it was fixed in the upstream sax-js? If so - we could backport it with the test. I haven't updated (or used) this package in a while.

2022-08-30 06:51 UTC, SvanteRichter commented
Doesn't look like it, I think this bug is specific to the deno version. When trying to find the exact xml that leads to the issue it also moves around where it crashes when I edit sections before that, so I'll have a mediawikidump with pages 1, 2 and three and it crashes on 2 so I remove 1 and then it crashes on 3 instead. I have a 124KB extract of the swedish wikivoyage that we could use as a testcase if that's alright with you?

2022-08-30 07:27 UTC, Maxim-Mazurok commented
Yes, sounds good, please create a pr, maybe based on this one, I'll try to review it in coming days. Thanks!

2022-08-30 11:03 UTC, SvanteRichter commented
I created a test for it, but since the testsuite runs on node instead of deno the test does not fail without this fix...

2022-08-31 03:29 UTC, Maxim-Mazurok commented
> I created a test for it, but since the testsuite runs on node instead of deno the test does not fail without this fix...

ah, that's a good point.. haven't used deno in a while, is there a deno-based test-runner we could migrate to?

2022-08-31 03:32 UTC, Maxim-Mazurok commented
Actually, now that I think about it, it sounds like Deno has a bug, right? If it works fine on NodeJS, but on Deno we seem to get some weird issue - probably it's worth opening an issue in deno repo?

2022-09-01 07:49 UTC, kuboon commented
https://github.com/Maxim-Mazurok/sax-ts/blob/3326ad340953c1b50f1688c1791bf338d9768a8f/src/sax.ts#L365-L376

Some fields are initialized by `''` but others have `undefined` value.

https://github.com/Maxim-Mazurok/sax-ts/blob/3326ad340953c1b50f1688c1791bf338d9768a8f/src/sax.ts#L1244
this code accesses `undefined.length` and fail if any of these uninitialized values did not get input before `checkBufferLength()` is called.

2022-09-02 06:37 UTC, kuboon commented
If you wish, I can provide Deno test code and github actions.
I'm sorry I don't want to prepare nodejs test because I already said goodbye to nodejs 😜

2022-09-04 08:22 UTC, SvanteRichter commented
@kuboon So you mean that it is not a bug in Deno, right?

I added an extremely simple test (just parsing a file that fails on the master branch but works with this) in #6, running it in deno.

It seems like the travis-ci integration is a bit broken, so I added a config to run the CI in github actions. @Maxim-Mazurok do you mind moving the tests to github actions?

The github actions test run will not show up in my PR here because the config is just in my fork, but you can see a run on fork here: https://github.com/SahAssar/sax-ts/runs/8175187088?check_suite_focus=true

2022-09-05 00:18 UTC, kuboon commented
Thank you @SahAssar , I read your github workflow and it looks fine.

2022-09-05 15:26 UTC, SvanteRichter commented
Yeah, when I wrote a similar test, parsing the same file and ran the testsuite in node it did not fail. It's a bit weird but right now I just need it to work, not to understand it. I'm just happy to parse the full wikipedia dumps in deno again :)

2022-09-07 00:42 UTC, Maxim-Mazurok commented
Superseded by #6, thank you!

2022-09-07 00:42 UTC, closed without merging